import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/app/components/SessionWrapper";
import { Provider } from "react-redux";
import { Providers } from "./GlobalRedux/provider";
import Footer from "@/app/components/Footer";
import { useSession } from "next-auth/react";
import Header from "@/app/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          <Header />

          <Providers>{children}</Providers>
          <Footer />
        </body>
      </html>
    </SessionWrapper>
  );
}
